/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.8
 * Generated at: 2022-10-25 08:23:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.report;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reportList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/PJT_Finance/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Finance/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/PJT_Finance/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Finance/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1529893629898L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>﻿\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t$(\".pSearchYear\").change(function(){\r\n");
      out.write("\t\t\tvar pStartYear = $(\"#pStartYear\").val();\r\n");
      out.write("\t\t\tvar pEndYear = $(\"#pEndYear\").val();\r\n");
      out.write("\t\t\tvar chkYear = pEndYear;\r\n");
      out.write("\t\t\tvar pYearList = [];\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#chkYearList').children('option').remove();\r\n");
      out.write("\t\t\t$('#pYearList').val('');\r\n");
      out.write("\t\t\tvar html = '<option value = \"\">개년 선택</option>'\r\n");
      out.write("\t\t\tvar td = ''\r\n");
      out.write("\t\t\tvar chkYearList = ''\r\n");
      out.write("\t\t\tfor(var i=1; pStartYear <= chkYear; i++){\r\n");
      out.write("\t\t\t\tpYearList.push(chkYear);\r\n");
      out.write("\t\t\t\tif(i==1){\r\n");
      out.write("\t\t\t\t\tchkYearList += chkYear\r\n");
      out.write("\t\t\t\t\thtml += '<option value=\"'+chkYearList+'\">'+ (chkYear) +' </option>'\r\n");
      out.write("\t\t\t\t\ttd += '<td>'+(chkYear--)+'</td>'\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tchkYearList += ','+chkYear\r\n");
      out.write("\t\t\t\t\thtml += '<option value=\"'+chkYearList+'\">'+ pEndYear+' ~ '+(chkYear) +' </option>'\r\n");
      out.write("\t\t\t\t\ttd += '<td>'+(chkYear--)+'</td>'\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$('#pYearList').val(pYearList);\r\n");
      out.write("\t\t\t$('#chkYearList').append(html);\r\n");
      out.write("\t\t\t$('#head').append(td);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction goSearch(){\r\n");
      out.write("\t\tvar frm = document.searchForm;\r\n");
      out.write("\t\tvar pAccountIds = [];\r\n");
      out.write("\t\t$(\"input[name=pAccountId]:checked\").each(function(){\r\n");
      out.write("\t\t\tpAccountIds.push($(this).val());\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#pAccountIds\").val(pAccountIds);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({    \r\n");
      out.write("\t\t\ttype : 'post',           // 타입 (get, post, put 등등)    \r\n");
      out.write("\t\t\turl : '/report/select',           // 요청할 서버url    \r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\tpYearList : $(\"#pYearList\").val(),\r\n");
      out.write("\t\t\t\tpStartYear : $(\"#pStartYear\").val(),\r\n");
      out.write("\t\t\t\tpEndYear : $(\"#pEndYear\").val(),\r\n");
      out.write("\t\t\t\tpReportCd : $(\"#pReportCd\").val(),\r\n");
      out.write("\t\t\t\tchkAccRate : $(\"#chkAccRate\").val(),\r\n");
      out.write("\t\t\t\tchkYearList : $(\"#chkYearList\").val(),\r\n");
      out.write("\t\t\t\tpAccountIds : $(\"#pAccountIds\").val()\r\n");
      out.write("\t\t\t},    \r\n");
      out.write("\t\t\tdataType : 'json',    \r\n");
      out.write("\t\t\tsuccess : function(data) { // 결과 성공 콜백함수        \r\n");
      out.write("\t\t\t\tvar resultList = data.resultList;\r\n");
      out.write("\t\t\t\tvar yearList = data.pYearList;\r\n");
      out.write("\t\t\t\t $(\"#userList\").dataTable({\r\n");
      out.write("\t\t\t\t \t data: resultList,\r\n");
      out.write("\t\t\t\t \t columns: [\r\n");
      out.write("\t\t\t\t  \t\t{ data: 'RNUM' },\r\n");
      out.write("\t\t\t\t  \t\t{ data: 'CORP_NAME' },\r\n");
      out.write("\t\t\t\t       \t{ data: 'ACCOUNT_ID' },\r\n");
      out.write("\t\t\t\t       \tfor(var j=0; j<yearList.length; j++){\r\n");
      out.write("\t\t\t\t\t\t\tvar name = 'RATE_'+yearList[j];\r\n");
      out.write("\t\t\t\t\t\t\t{ data: name },\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t  \t]\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t /* \r\n");
      out.write("\t\t\t\tfor(var i=0; i<resultList.length; i++){\r\n");
      out.write("\t\t\t\t\tvar html = ''\r\n");
      out.write("\t\t\t\t\thtml += '<tr>'\r\n");
      out.write("\t\t\t\t\thtml +=\t'<td>'+resultList[i].RNUM+'</td>'\r\n");
      out.write("\t\t\t\t\thtml +=\t'<td>'+resultList[i].CORP_NAME+'</td>'\r\n");
      out.write("\t\t\t\t\thtml +=\t'<td>'+resultList[i].ACCOUNT_ID+'</td>'\r\n");
      out.write("\t\t\t\t\tfor(var j=0; j<yearList.length; j++){\r\n");
      out.write("\t\t\t\t\t\tvar name = 'RATE_'+yearList[j];\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"JB1 : \"+name);\r\n");
      out.write("\t\t\t\t\t\thtml +=\t'<td>'+resultList[i].name+'</td>'\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"JB21 : \"+resultList[i].name);\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"JB22 : \"+resultList[i].RATE_2021);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\thtml += '</tr>'\r\n");
      out.write("\t\t\t\t\t$('#bodyList').append(html);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t */\r\n");
      out.write("\t\t\t},    \r\n");
      out.write("\t\t\terror : function(request, status, error) {       \r\n");
      out.write("\t\t\t\tconsole.log(error)    \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>사업장 목록</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("\t<form name=\"searchForm\" method=\"post\">\r\n");
      out.write("\t<!-- Page Heading -->\r\n");
      out.write("\t<h1 class=\"h3 mb-2 text-gray-800\">종목발굴</h1>\r\n");
      out.write("\t<p class=\"mb-4\"></p>\r\n");
      out.write("\r\n");
      out.write("\t<!-- DataTales Example -->\r\n");
      out.write("    <div class=\"card shadow mb-4\">\r\n");
      out.write("        <div class=\"card-header py-3\">\r\n");
      out.write("            <h6 class=\"m-0 font-weight-bold text-primary\">조회조건</h6>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("            <div class=\"table-responsive\">\r\n");
      out.write("                <table class=\"table table-bordered\"  width=\"100%\" cellspacing=\"0\">\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>조회 년도</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"pYearList\" id=\"pYearList\" value=\"\" title=\"조회 년도 목록\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"pStartYear\" id=\"pStartYear\" class=\"pSearchYear\" value=\"\" title=\"조회 시작년도\"> ~ <input type=\"text\" name=\"pEndYear\" id=\"pEndYear\" class=\"pSearchYear\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${curYear-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" title=\"조회 시작년도\">  \r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>보고서 구분</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"radio\" name=\"pReportCd\" id=\"pReportCd\" value=\"11011\" title=\"보고서 구분\"> 년도 <input type=\"radio\" name=\"pReportCd\" id=\"pReportCd\" value=\"11012\" title=\"보고서 구분\"> 반기 </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>기준 성장률</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" name=\"chkAccRate\" id=\"chkAccRate\" value=\"\" title=\"기준 성장률\">  </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>기준 개년</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"chkYearList\" id=\"chkYearList\" title=\"기준 년도 선택\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value = \"\">개년 선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select> \r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>조회 계정</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td rowspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"pAccountIds\" id=\"pAccountIds\" value=\"\" title=\"계정 목록\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"pAccountId\" id=\"pAccountId\" value=\"ifrs-full_Revenue\" title=\"매출액\"> 매출액 \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"pAccountId\" id=\"pAccountId\" value=\"dart_OperatingIncomeLoss\" title=\"영업이익\"> 영업이익\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"pAccountId\" id=\"pAccountId\" value=\"ifrs-full_ProfitLoss\" title=\"당기순이익\"> 당기순이익 \r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("                <a href=\"\" onclick=\"goSearch(); return false;\" class=\"btn btn-primary btn-icon-split btn-sm\">\r\n");
      out.write("                     <span class=\"icon text-white-50\">\r\n");
      out.write("                         <i class=\"fas fa-flag\"></i>\r\n");
      out.write("                     </span>\r\n");
      out.write("                     <span class=\"text\">조 회</span>\r\n");
      out.write("               \t</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Page Heading -->\r\n");
      out.write("\t<h1 class=\"h3 mb-2 text-gray-800\">Tables</h1>\r\n");
      out.write("\t<p class=\"mb-4\">DataTables is a third party plugin that is used to generate the demo table below.\r\n");
      out.write("\t    For more information about DataTables, please visit the <a target=\"_blank\"\r\n");
      out.write("\t        href=\"https://datatables.net\">official DataTables documentation</a>.</p>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- DataTales Example -->\r\n");
      out.write("    <div class=\"card shadow mb-4\">\r\n");
      out.write("        <div class=\"card-header py-3\">\r\n");
      out.write("            <h6 class=\"m-0 font-weight-bold text-primary\">DataTables Example</h6>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("            <div class=\"table-responsive\">\r\n");
      out.write("                <table id=\"userList\" class=\"table table-bordered\" id=\"dataTable\" width=\"100%\" >\r\n");
      out.write("                    <thead>\r\n");
      out.write("\t\t\t            <tr id=\"head\">\r\n");
      out.write("\t\t\t            \t<td>No</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>사업장명</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>계정명</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t        </thead>\r\n");
      out.write("\t\t\t        <tbody id=\"bodyList\">\r\n");
      out.write("\t\t\t        </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t<p>\r\n");
      out.write("\t\t<a onclick=\"goSearch(); return false;\">검색123</a>\r\n");
      out.write("\t</p>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
