/*
 * Generated by the Jasper component of Apache Tomcat
<<<<<<< HEAD
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2022-11-19 13:47:09 UTC
=======
 * Version: Apache Tomcat/9.0.8
 * Generated at: 2022-11-18 07:30:43 UTC
>>>>>>> 844a58f86eba82bf22f4b63666f11ea8363e93f4
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.portfolio;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class portfolioList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/PJT_Finance/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Finance/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/PJT_Finance/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Finance/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
<<<<<<< HEAD
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1658839109144L));
=======
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1529893629898L));
>>>>>>> 844a58f86eba82bf22f4b63666f11ea8363e93f4
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
<<<<<<< HEAD
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
=======
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
>>>>>>> 844a58f86eba82bf22f4b63666f11ea8363e93f4
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

<<<<<<< HEAD
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>﻿\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	var toggleChk = true;\n");
      out.write("	$(document).ready(function(){\n");
      out.write("		\n");
      out.write("		$(\"#portCorpList\").dataTable({\n");
      out.write("			lengthMenu: [ 12, 18, 24, 30, 36 ],\n");
      out.write("		 	data: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${getPortCorpJson}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(",\n");
      out.write("		 	destroy: true,\n");
      out.write("		 	columns: [\n");
      out.write("		  		{ \"data\": '',\n");
      out.write("		  			\"defaultContent\" : '',\n");
      out.write("		  			\"render\": function(data, type, row, meta){\n");
      out.write("		  	            if(type === 'display'){\n");
      out.write("		  	            	data = '<input type=\"checkbox\" name=\"del_chk\" id=\"del_chk\" value=\"'+row.CORP_CODE+'\" title=\"삭제 체크박스\">';\n");
      out.write("		  	            }\n");
      out.write("\n");
      out.write("		  	            return data;\n");
      out.write("		  	         }	 \n");
      out.write("		  		},\n");
      out.write("		  		{ \"data\": 'INVEST_OPINION', \n");
      out.write("		  			\"render\": function(data, type, row, meta){\n");
      out.write("		  				if(row.INVEST_OPINION != null && row.INVEST_OPINION != ''){\n");
      out.write("		  					if(type === 'display'){\n");
      out.write("		  						var style = '';\n");
      out.write("		  						if(row.INVEST_OPINION == '매수'){\n");
      out.write("		  							style = \"style='color: red;'\";\n");
      out.write("		  						}else if(row.INVEST_OPINION == '비중확대'){\n");
      out.write("		  							style = \"style='color: palevioletred;'\";\n");
      out.write("		  						}else if(row.INVEST_OPINION == '중립'){\n");
      out.write("		  							style = \"style='color: black;'\";\n");
      out.write("		  						}\n");
      out.write("		  						else if(row.INVEST_OPINION == '비중축소'){\n");
      out.write("		  							style = \"style='color: cornflowerblue;'\";\n");
      out.write("		  						}\n");
      out.write("		  						else if(row.INVEST_OPINION == '매도'){\n");
      out.write("		  							style = \"style='color: blue;'\";\n");
      out.write("		  						}else{\n");
      out.write("		  							style = \"\";\n");
      out.write("		  						}\n");
      out.write("			  	                data = '<span '+style+'>'+row.INVEST_OPINION+'( ~ '+row.INVEST_OPINION_AMOUNT+' )</span>';\n");
      out.write("			  	            }		  					\n");
      out.write("		  				}else{\n");
      out.write("		  					data = \"없음\";\n");
      out.write("		  				}\n");
      out.write("\n");
      out.write("		  	            return data;\n");
      out.write("		  	         }	\n");
      out.write("		  		},\n");
      out.write("		  		{ data: 'CORP_NAME' },\n");
      out.write("		  		{ \"data\": 'BEF_CLS_PRICE', \n");
      out.write("		  			\"defaultContent\" : '',\n");
      out.write("		  			\"render\": function(data, type, row, meta){\n");
      out.write("		  				if(row.BEF_CLS_PRICE != null && row.BEF_CLS_PRICE != ''){\n");
      out.write("		  					if(type === 'display'){\n");
      out.write("			  	                data = row.BEF_CLS_PRICE;\n");
      out.write("			  	            }		  					\n");
      out.write("		  				}else{\n");
      out.write("		  					data = \"없음\";\n");
      out.write("		  				}\n");
      out.write("\n");
      out.write("		  	            return data;\n");
      out.write("		  	         }	\n");
      out.write("		  		},\n");
      out.write("		  		{ \"data\": 'AVR_PRICE', \n");
      out.write("		  			\"render\": function(data, type, row, meta){\n");
      out.write("		  				if(row.AVR_PRICE != null && row.AVR_PRICE != ''){\n");
      out.write("		  					if(type === 'display'){\n");
      out.write("		  						var style = '';\n");
      out.write("		  						if(row.AVR_PRICE < row.BEF_CLS_PRICE){\n");
      out.write("		  							style = \"style='color: palevioletred;'\";\n");
      out.write("		  						}else if(row.AVR_PRICE > row.BEF_CLS_PRICE){\n");
      out.write("		  							style = \"style='color: cornflowerblue;'\";\n");
      out.write("		  						}\n");
      out.write("		  						else{\n");
      out.write("		  							style = \"\";\n");
      out.write("		  						}\n");
      out.write("			  	                data = '<span '+style+'>'+row.AVR_PRICE+'</span>';\n");
      out.write("			  	            }		  					\n");
      out.write("		  				}else{\n");
      out.write("		  					data = \"없음\";\n");
      out.write("		  				}\n");
      out.write("\n");
      out.write("		  	            return data;\n");
      out.write("		  	         }	\n");
      out.write("		  		},\n");
      out.write("		  		{ \"data\": 'HOLD_QUANTITY', \n");
      out.write("		  			\"render\": function(data, type, row, meta){\n");
      out.write("		  				if(row.HOLD_QUANTITY != null && row.HOLD_QUANTITY != ''){\n");
      out.write("		  					if(type === 'display'){\n");
      out.write("			  	                data = row.HOLD_QUANTITY;\n");
      out.write("			  	            }		  					\n");
      out.write("		  				}else{\n");
      out.write("		  					data = \"없음\";\n");
      out.write("		  				}\n");
      out.write("\n");
      out.write("		  	            return data;\n");
      out.write("		  	         }	\n");
      out.write("		  		},\n");
      out.write("		  		{ \"data\": '', \n");
      out.write("		  			\"defaultContent\" : '',\n");
      out.write("		  			\"render\": function(data, type, row, meta){\n");
      out.write("		  	            if(type === 'display'){\n");
      out.write("		  	                data = '<a href=\"#\" onclick=\"openReportPop(\\''+row.REPRT_NO+'\\',\\''+row.REPRT_NM+'\\')\" >'+row.REPRT_NM+'</a>';\n");
      out.write("		  	            }\n");
      out.write("\n");
      out.write("		  	            return data;\n");
      out.write("		  	         }	\n");
      out.write("		  		},\n");
      out.write("		  		{ \"data\": '',\n");
      out.write("		  			\"defaultContent\" : '',\n");
      out.write("		  			\"render\": function(data, type, row, meta){\n");
      out.write("		  	            if(type === 'display'){\n");
      out.write("		  	            	 data = '<a href=\"#\" onclick=\"openReportList(\\''+row.CORP_CODE+'\\',\\''+row.CORP_NAME+'\\')\" class=\"btn btn-light btn-icon-split\"><span class=\"icon text-gray-600\"><i class=\"fas fa-flag\"></i></span></a>';\n");
      out.write("		  	            }\n");
      out.write("\n");
      out.write("		  	            return data;\n");
      out.write("		  	         }	 \n");
      out.write("		  		},\n");
      out.write("		  		{ \"data\": '',\n");
      out.write("		  			\"defaultContent\" : '',\n");
      out.write("		  			\"render\": function(data, type, row, meta){\n");
      out.write("		  	            if(type === 'display'){\n");
      out.write("		  	            	data = '<a href=\"#\" onclick=\"goPortfolioDetail(\\''+row.CORP_CODE+'\\')\" class=\"btn btn-info btn-circle btn-sm\"><i class=\"fas fa-info-circle\"></i></a>';\n");
      out.write("		  	            }\n");
      out.write("\n");
      out.write("		  	            return data;\n");
      out.write("		  	         }	 \n");
      out.write("		  		},\n");
      out.write("		  		{ \"data\": 'MEMO', \n");
      out.write("		  			\"render\": function(data, type, row, meta){\n");
      out.write("		  				if(row.MEMO != null && row.MEMO != ''){\n");
      out.write("		  					if(type === 'display'){\n");
      out.write("		  						data = '<a href=\"#\" onclick=\"openMemoPop(\\''+row.CORP_CODE+'\\'); return false;\" style=\"border-color: #FFD232; background: #FFD232;\" class=\"btn btn-info btn-circle btn-sm\"><i class=\"fas fa-clipboard-list\"></i></a>';\n");
      out.write("			  	            }		  					\n");
      out.write("		  				}else{\n");
      out.write("		  					data = '<a href=\"#\" onclick=\"openMemoPop(\\''+row.CORP_CODE+'\\'); return false;\" style=\"border-color: #aeafb9; background: #aeafb9;\" class=\"btn btn-info btn-circle btn-sm\"><i class=\"fas fa-clipboard-list\"></i></a>';\n");
      out.write("		  				}\n");
      out.write("\n");
      out.write("		  	            return data;\n");
      out.write("		  	         }	\n");
      out.write("		  		}\n");
      out.write("		  	]\n");
      out.write("		});\n");
      out.write("		\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	function delInterest(corpCd,corpNm,stockCd){\n");
      out.write("		var frm = document.form;\n");
      out.write("		\n");
      out.write("		if(!confirm('\\''+corpNm+'\\'을 관심목록에서 삭제하시겠습니까?')) return;\n");
      out.write("		\n");
      out.write("		$(\"#corpCd\").val(corpCd);\n");
      out.write("		$(\"#corpNm\").val(corpNm);\n");
      out.write("		$(\"#stockCd\").val(stockCd);\n");
      out.write("		\n");
      out.write("		frm.action = \"/interest/del/cud\";\n");
      out.write("		frm.submit();\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	function addPortfolio(corpCd,corpNm,stockCd){\n");
      out.write("		var url = \"/portfolio/add/cud\";\n");
      out.write("		\n");
      out.write("		if(!confirm('\\''+corpNm+'\\'을 포트폴리오에 추가하시겠습니까?')) return;\n");
      out.write("		\n");
      out.write("		$.ajax({    \n");
      out.write("			type : 'post',           // 타입 (get, post, put 등등)    \n");
      out.write("			url : url,           // 요청할 서버url    \n");
      out.write("			data : {\n");
      out.write("				CORP_CODE 	: corpCd,\n");
      out.write("				CORP_NAME	: corpNm,\n");
      out.write("				STOCK_CODE 	: stockCd,\n");
      out.write("			},    \n");
      out.write("			dataType : 'json',    \n");
      out.write("			success : function(data) { // 결과 성공 콜백함수        \n");
      out.write("				$('#dataTables').css(\"animation-name\",\"add\");\n");
      out.write("				$('#dataTables').css(\"animation-duration\",\"2.5s\");\n");
      out.write("			},    \n");
      out.write("			error : function(request, status, error) {       \n");
      out.write("				console.log(error)    \n");
      out.write("			}\n");
      out.write("		})\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	function openMemoPop(corpCd){\n");
      out.write("        var url = \"/popup/portfolio/memo?pCorpCd=\"+corpCd;\n");
      out.write("        var name = \"포트폴리오 메모 팝업\";\n");
      out.write("        var option = \"width = 505, height = 780, top = 100, left = 200, location = no\"\n");
      out.write("        window.open(url, name, option);\n");
      out.write("    }\n");
      out.write("	\n");
      out.write("	function openReportPop(reprtNo,reprtNm){\n");
      out.write("        var url = \"https://dart.fss.or.kr/dsaf001/main.do?rcpNo=\"+reprtNo;\n");
      out.write("        var name = reprtNm;\n");
      out.write("        var option = \"width = 500, height = 1500, top = 100, left = 200, location = no\"\n");
      out.write("        window.open(url, name, option);\n");
      out.write("    }\n");
      out.write("	\n");
      out.write("	function openReportList(corpCd,corpNm){\n");
      out.write("        var url = \"/popup/dart/report/list?corpCd=\"+corpCd;\n");
      out.write("        var name = corpNm + \" 공시 목록\";\n");
      out.write("        var option = \"width = 1000, height = 700, top = 100, left = 200, location = no\"\n");
      out.write("        window.open(url, name, option);\n");
      out.write("    }\n");
      out.write("	\n");
      out.write("	function delPortCorp(){\n");
      out.write("		var frm = document.searchForm;\n");
      out.write("		var delChks = \"\";\n");
      out.write("		\n");
      out.write("		var i = 0;\n");
      out.write("		$(\"input[name=del_chk]:checked\").each(function(){\n");
      out.write("			if(i==0){\n");
      out.write("				delChks += $(this).val();\n");
      out.write("			}else{\n");
      out.write("				delChks += \",\"+$(this).val();\n");
      out.write("			}\n");
      out.write("			i++;\n");
      out.write("		});\n");
      out.write("		\n");
      out.write("		if(i == 0){\n");
      out.write("			alert(\"삭제할 사업장을 선택해 주세요.\");\n");
      out.write("			return;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		var corpCd = \"\";\n");
      out.write("		\n");
      out.write("		if(!confirm('체크된 사업장을 포트폴리오에서 삭제하시겠습니까?')) return;\n");
      out.write("		\n");
      out.write("		$(\"#corpCds\").val(delChks);\n");
      out.write("		\n");
      out.write("		frm.action = \"/portfolio/del/cud\";\n");
      out.write("		frm.submit();\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	function regAsset(gu){\n");
      out.write("		var url = \"/portfolio/regasset/cud\";\n");
      out.write("		\n");
      out.write("		var guTitle = \"\";\n");
      out.write("		var guVal = \"\";\n");
      out.write("		if(gu == 'deposit'){\n");
      out.write("			guVal = $(\"#DEPOSIT_AMOUNT\").val();\n");
      out.write("			guTitle = $(\"#DEPOSIT_AMOUNT\").attr(\"title\");\n");
      out.write("		}else{\n");
      out.write("			guVal = $(\"#RESERVE_AMOUNT\").val();\n");
      out.write("			guTitle =  $(\"#RESERVE_AMOUNT\").attr(\"title\");\n");
      out.write("		}\n");
      out.write("\n");
      out.write("		guVal = guVal.toString().replace(/\\B(?<!\\.\\d*)(?=(\\d{3})+(?!\\d))/g, \",\");\n");
      out.write("		\n");
      out.write("		alert(guTitle + \" : \"+guVal+\" 원 등록 하시겠습니까?\");\n");
      out.write("		\n");
      out.write("		$.ajax({    \n");
      out.write("			type : 'post',           // 타입 (get, post, put 등등)    \n");
      out.write("			url : url,           // 요청할 서버url    \n");
      out.write("			data : {\n");
      out.write("				DEPOSIT_AMOUNT 	: $(\"#DEPOSIT_AMOUNT\").val(),\n");
      out.write("				RESERVE_AMOUNT	: $(\"#RESERVE_AMOUNT\").val(),\n");
      out.write("			},    \n");
      out.write("			dataType : 'json',    \n");
      out.write("			success : function(data) { // 결과 성공 콜백함수\n");
      out.write("				var resultData = data.resultData;\n");
      out.write("				if(gu == 'deposit'){\n");
      out.write("					$(\"btn_DEPOSIT_AMOUNT\").text('수정');\n");
      out.write("					$(\"#DEPOSIT_AMOUNT\").val(resultData.DEPOSIT_AMOUNT);\n");
      out.write("				}else{\n");
      out.write("					$(\"btn_RESERVE_AMOUNT\").text('수정');\n");
      out.write("					$(\"#RESERVE_AMOUNT\").val(resultData.RESERVE_AMOUNT);\n");
      out.write("				}\n");
      out.write("				$('#cardDiv').css(\"animation-name\",\"add\");\n");
      out.write("				$('#cardDiv').css(\"animation-duration\",\"2.5s\");\n");
      out.write("			},    \n");
      out.write("			error : function(request, status, error) {       \n");
      out.write("				console.log(error)    \n");
      out.write("			}\n");
      out.write("		})\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	function goPortfolioDetail(corpCd){\n");
      out.write("		var frm = document.searchForm;\n");
      out.write("		\n");
      out.write("		$(\"#pCorpCd\").val(corpCd);\n");
      out.write("		\n");
      out.write("		frm.action = \"/portfolio/detail\";\n");
      out.write("		frm.target = \"_blank\"\n");
      out.write("		frm.submit();\n");
      out.write("	}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("@keyframes add {\n");
      out.write("	from{background : lightgreen;}\n");
      out.write("	to{background : transparent;}\n");
      out.write("}\n");
      out.write("\n");
      out.write("@keyframes del {\n");
      out.write("	from{background : indianred;}\n");
      out.write("	to{background : transparent;}\n");
      out.write("}\n");
      out.write("\n");
      out.write("@keyframes search {\n");
      out.write("	from{background : lightsteelblue;}\n");
      out.write("	to{background : transparent;}\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>사업장 목록</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"container-fluid\">\n");
      out.write("	<form name=\"searchForm\" method=\"post\">\n");
      out.write("	<input type=\"hidden\" name=\"CORP_CODE\" id=\"CORP_CODE\" value=\"\" title=\"기업 코드\">\n");
      out.write("	<input type=\"hidden\" name=\"STOCK_CODE\" id=\"STOCK_CODE\" value=\"\" title=\"기업 코드\">\n");
      out.write("	\n");
      out.write("	<input type=\"hidden\" name=\"pCorpCd\" id=\"pCorpCd\" value=\"\" title=\"검색용 기업 코드\">\n");
      out.write("	\n");
      out.write("	<input type=\"hidden\" name=\"corpCds\" id=\"corpCds\" value=\"\" title=\"삭제대상 사업장코드(복수)\">\n");
      out.write("    </form>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"container-fluid\">\n");
      out.write("\n");
      out.write("	<!-- Page Heading -->\n");
      out.write("	<h1 class=\"h3 mb-2 text-gray-800\">포트폴리오</h1>\n");
      out.write("	<p class=\"mb-4\">본인이 보유하고 있는 기업에 대한 포트폴리오 리스트 \n");
      out.write("		<span id=\"\"></span>\n");
      out.write("	</p>\n");
      out.write("	\n");
      out.write("	<div class=\"col-xl-4 col-lg-5\">\n");
      out.write("	    <div class=\"card shadow mb-4\" id=\"cardDiv\">\n");
      out.write("	        <!-- Card Header - Dropdown -->\n");
      out.write("	        <div class=\"card-header py-3 d-flex flex-row align-items-center justify-content-between\">\n");
      out.write("	            <h6 class=\"m-0 font-weight-bold text-primary\">포트폴리오 자산 분배비율</h6>\n");
      out.write("	            <div class=\"dropdown no-arrow\">\n");
      out.write("	                <a class=\"dropdown-toggle\" href=\"#\" role=\"button\" id=\"dropdownMenuLink\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("	                    <i class=\"fas fa-ellipsis-v fa-sm fa-fw text-gray-400\"></i>\n");
      out.write("	                </a>\n");
      out.write("	                <div class=\"dropdown-menu dropdown-menu-right shadow animated--fade-in\" aria-labelledby=\"dropdownMenuLink\">\n");
      out.write("	                    <div class=\"dropdown-header\" style=\"font-size: 12px;\">- 자산 등록 -</div>\n");
      out.write("	                    <div class=\"dropdown-divider\"></div>\n");
      out.write("	                    <div style=\"padding: 5px 10px 5px 10px;\">\n");
      out.write("		                    <div class=\"dropdown-item\" style=\"padding: 10px 10px 10px 10px;\">\n");
      out.write("			                    예수금 : <input type=\"text\" name=\"DEPOSIT_AMOUNT\" id=\"DEPOSIT_AMOUNT\" style=\"width : 135px;\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${getPortfolio.DEPOSIT_AMOUNT }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  title=\"예수금\" placeholder=\"예수금\"> \n");
      out.write("			                    <button class=\"btn btn-outline-primary\" style=\"height: 30px; font-size: 13px; width: 55px;\" id=\"btn_DEPOSIT_AMOUNT\" onclick=\"regAsset('deposit'); return false;\">\n");
      out.write("			                    	");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("			                    	");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("			                    </button>\n");
      out.write("		                    </div>\n");
      out.write("		                    <div class=\"dropdown-divider\"></div>\n");
      out.write("		                    <div class=\"dropdown-item\" style=\"padding: 10px 10px 10px 10px;\">\n");
      out.write("			                    예비금 : <input type=\"text\" name=\"RESERVE_AMOUNT\" id=\"RESERVE_AMOUNT\" style=\"width : 135px;\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${getPortfolio.RESERVE_AMOUNT }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  title=\"예비금\" placeholder=\"예비금\"> \n");
      out.write("			                    <button class=\"btn btn-outline-primary\" style=\"height: 30px; font-size: 13px; width: 55px;\" id=\"btn_RESERVE_AMOUNT\" onclick=\"regAsset('reserve'); return false;\">\n");
      out.write("			                    	");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("			                    	");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write(" \n");
      out.write("			                    </button>\n");
      out.write("		                    </div>\n");
      out.write("	                    </div>\n");
      out.write("	                </div>\n");
      out.write("	            </div>\n");
      out.write("	        </div>\n");
      out.write("	        <!-- Card Body -->\n");
      out.write("	        <div class=\"card-body\">\n");
      out.write("	            <div class=\"chart-pie pt-4 pb-2\"><div class=\"chartjs-size-monitor\"><div class=\"chartjs-size-monitor-expand\"><div class=\"\"></div></div><div class=\"chartjs-size-monitor-shrink\"><div class=\"\"></div></div></div>\n");
      out.write("	                <canvas id=\"myPieChart\" width=\"470\" height=\"245\" style=\"display: block; width: 470px; height: 245px;\" class=\"chartjs-render-monitor\"></canvas>\n");
      out.write("	            </div>\n");
      out.write("	            <div class=\"mt-4 text-center small\">\n");
      out.write("	                <span class=\"mr-2\">\n");
      out.write("	                    <i class=\"fas fa-circle text-primary\"></i> 예수금\n");
      out.write("	                </span>\n");
      out.write("	                <span class=\"mr-2\">\n");
      out.write("	                    <i class=\"fas fa-circle text-success\"></i> 투자금\n");
      out.write("	                </span>\n");
      out.write("	                <span class=\"mr-2\">\n");
      out.write("	                    <i class=\"fas fa-circle text-info\"></i> 예비금\n");
      out.write("	                </span>\n");
      out.write("	            </div>\n");
      out.write("	        </div>\n");
      out.write("	    </div>\n");
      out.write("	</div>\n");
      out.write("		\n");
      out.write("	<!-- DataTales Example -->\n");
      out.write("    <div class=\"card shadow mb-4\">\n");
      out.write("        <div class=\"card-header py-3\" id=\"dataTables\" style=\"display: table;\">\n");
      out.write("            <h6 class=\"m-0 font-weight-bold text-primary\" style=\"display: table-cell; width: 95%; padding-left: 10px;\">포트폴리오 기업목록</h6>\n");
      out.write("            <div >\n");
      out.write("				<button class=\"dt-button buttons-excel buttons-html5 btn btn-outline-primary excelBtn\" style=\"width: 70px;\" tabindex=\"0\" aria-controls=\"portCorpList\" onclick=\"delPortCorp(); return false;\">\n");
      out.write("					<span>삭제</span>\n");
      out.write("				</button>                	\n");
      out.write("			</div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"card-body\">\n");
      out.write("            <div class=\"table-responsive\" >\n");
      out.write("                <table id=\"portCorpList\" class=\"table table-bordered\" id=\"dataTable\" width=\"100%\" >\n");
      out.write("                    <thead id=\"tableHead\">\n");
      out.write("			            <tr>\n");
      out.write("			            	<td></td>\n");
      out.write("							<td>투자의견</td>\n");
      out.write("							<td>사업장명</td>\n");
      out.write("							<td>전일종가</td>\n");
      out.write("							<td>평균단가</td>\n");
      out.write("							<td>보유수량</td>\n");
      out.write("							<td>최근공시명</td>\n");
      out.write("							<td>공시목록</td>\n");
      out.write("							<td>상세</td>\n");
      out.write("							<td>메모</td>\n");
      out.write("						</tr>\n");
      out.write("			        </thead>\n");
      out.write("			        <tbody id=\"bodyList\">\n");
      out.write("			        </tbody>\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
=======
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>﻿\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar toggleChk = true;\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#portCorpList\").dataTable({\r\n");
      out.write("\t\t\tlengthMenu: [ 12, 18, 24, 30, 36 ],\r\n");
      out.write("\t\t \tdata: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${getPortCorpJson}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(",\r\n");
      out.write("\t\t \tdestroy: true,\r\n");
      out.write("\t\t \tcolumns: [\r\n");
      out.write("\t\t  \t\t{ \"data\": '',\r\n");
      out.write("\t\t  \t\t\t\"defaultContent\" : '',\r\n");
      out.write("\t\t  \t\t\t\"render\": function(data, type, row, meta){\r\n");
      out.write("\t\t  \t            if(type === 'display'){\r\n");
      out.write("\t\t  \t            \tdata = '<input type=\"checkbox\" name=\"del_chk\" id=\"del_chk\" value=\"'+row.CORP_CODE+'\" title=\"삭제 체크박스\">';\r\n");
      out.write("\t\t  \t            }\r\n");
      out.write("\r\n");
      out.write("\t\t  \t            return data;\r\n");
      out.write("\t\t  \t         }\t \r\n");
      out.write("\t\t  \t\t},\r\n");
      out.write("\t\t  \t\t{ \"data\": 'INVEST_OPINION', \r\n");
      out.write("\t\t  \t\t\t\"render\": function(data, type, row, meta){\r\n");
      out.write("\t\t  \t\t\t\tif(row.INVEST_OPINION != null && row.INVEST_OPINION != ''){\r\n");
      out.write("\t\t  \t\t\t\t\tif(type === 'display'){\r\n");
      out.write("\t\t  \t\t\t\t\t\tvar style = '';\r\n");
      out.write("\t\t  \t\t\t\t\t\tif(row.INVEST_OPINION == '매수'){\r\n");
      out.write("\t\t  \t\t\t\t\t\t\tstyle = \"style='color: red;'\";\r\n");
      out.write("\t\t  \t\t\t\t\t\t}else if(row.INVEST_OPINION == '비중확대'){\r\n");
      out.write("\t\t  \t\t\t\t\t\t\tstyle = \"style='color: palevioletred;'\";\r\n");
      out.write("\t\t  \t\t\t\t\t\t}else if(row.INVEST_OPINION == '중립'){\r\n");
      out.write("\t\t  \t\t\t\t\t\t\tstyle = \"style='color: black;'\";\r\n");
      out.write("\t\t  \t\t\t\t\t\t}\r\n");
      out.write("\t\t  \t\t\t\t\t\telse if(row.INVEST_OPINION == '비중축소'){\r\n");
      out.write("\t\t  \t\t\t\t\t\t\tstyle = \"style='color: cornflowerblue;'\";\r\n");
      out.write("\t\t  \t\t\t\t\t\t}\r\n");
      out.write("\t\t  \t\t\t\t\t\telse if(row.INVEST_OPINION == '매도'){\r\n");
      out.write("\t\t  \t\t\t\t\t\t\tstyle = \"style='color: blue;'\";\r\n");
      out.write("\t\t  \t\t\t\t\t\t}else{\r\n");
      out.write("\t\t  \t\t\t\t\t\t\tstyle = \"\";\r\n");
      out.write("\t\t  \t\t\t\t\t\t}\r\n");
      out.write("\t\t\t  \t                data = '<span '+style+'>'+row.INVEST_OPINION+'( ~ '+row.INVEST_OPINION_AMOUNT+' )</span>';\r\n");
      out.write("\t\t\t  \t            }\t\t  \t\t\t\t\t\r\n");
      out.write("\t\t  \t\t\t\t}else{\r\n");
      out.write("\t\t  \t\t\t\t\tdata = \"없음\";\r\n");
      out.write("\t\t  \t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t  \t            return data;\r\n");
      out.write("\t\t  \t         }\t\r\n");
      out.write("\t\t  \t\t},\r\n");
      out.write("\t\t  \t\t{ data: 'CORP_NAME' },\r\n");
      out.write("\t\t  \t\t{ \"data\": 'BEF_CLS_PRICE', \r\n");
      out.write("\t\t  \t\t\t\"defaultContent\" : '',\r\n");
      out.write("\t\t  \t\t\t\"render\": function(data, type, row, meta){\r\n");
      out.write("\t\t  \t\t\t\tif(row.BEF_CLS_PRICE != null && row.BEF_CLS_PRICE != ''){\r\n");
      out.write("\t\t  \t\t\t\t\tif(type === 'display'){\r\n");
      out.write("\t\t\t  \t                data = row.BEF_CLS_PRICE;\r\n");
      out.write("\t\t\t  \t            }\t\t  \t\t\t\t\t\r\n");
      out.write("\t\t  \t\t\t\t}else{\r\n");
      out.write("\t\t  \t\t\t\t\tdata = \"없음\";\r\n");
      out.write("\t\t  \t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t  \t            return data;\r\n");
      out.write("\t\t  \t         }\t\r\n");
      out.write("\t\t  \t\t},\r\n");
      out.write("\t\t  \t\t{ \"data\": 'AVR_PRICE', \r\n");
      out.write("\t\t  \t\t\t\"render\": function(data, type, row, meta){\r\n");
      out.write("\t\t  \t\t\t\tif(row.AVR_PRICE != null && row.AVR_PRICE != ''){\r\n");
      out.write("\t\t  \t\t\t\t\tif(type === 'display'){\r\n");
      out.write("\t\t  \t\t\t\t\t\tvar style = '';\r\n");
      out.write("\t\t  \t\t\t\t\t\tif(row.AVR_PRICE < row.BEF_CLS_PRICE){\r\n");
      out.write("\t\t  \t\t\t\t\t\t\tstyle = \"style='color: palevioletred;'\";\r\n");
      out.write("\t\t  \t\t\t\t\t\t}else if(row.AVR_PRICE > row.BEF_CLS_PRICE){\r\n");
      out.write("\t\t  \t\t\t\t\t\t\tstyle = \"style='color: cornflowerblue;'\";\r\n");
      out.write("\t\t  \t\t\t\t\t\t}\r\n");
      out.write("\t\t  \t\t\t\t\t\telse{\r\n");
      out.write("\t\t  \t\t\t\t\t\t\tstyle = \"\";\r\n");
      out.write("\t\t  \t\t\t\t\t\t}\r\n");
      out.write("\t\t\t  \t                data = '<span '+style+'>'+row.AVR_PRICE+'</span>';\r\n");
      out.write("\t\t\t  \t            }\t\t  \t\t\t\t\t\r\n");
      out.write("\t\t  \t\t\t\t}else{\r\n");
      out.write("\t\t  \t\t\t\t\tdata = \"없음\";\r\n");
      out.write("\t\t  \t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t  \t            return data;\r\n");
      out.write("\t\t  \t         }\t\r\n");
      out.write("\t\t  \t\t},\r\n");
      out.write("\t\t  \t\t{ \"data\": 'HOLD_QUANTITY', \r\n");
      out.write("\t\t  \t\t\t\"render\": function(data, type, row, meta){\r\n");
      out.write("\t\t  \t\t\t\tif(row.HOLD_QUANTITY != null && row.HOLD_QUANTITY != ''){\r\n");
      out.write("\t\t  \t\t\t\t\tif(type === 'display'){\r\n");
      out.write("\t\t\t  \t                data = row.HOLD_QUANTITY;\r\n");
      out.write("\t\t\t  \t            }\t\t  \t\t\t\t\t\r\n");
      out.write("\t\t  \t\t\t\t}else{\r\n");
      out.write("\t\t  \t\t\t\t\tdata = \"없음\";\r\n");
      out.write("\t\t  \t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t  \t            return data;\r\n");
      out.write("\t\t  \t         }\t\r\n");
      out.write("\t\t  \t\t},\r\n");
      out.write("\t\t  \t\t{ \"data\": '', \r\n");
      out.write("\t\t  \t\t\t\"defaultContent\" : '',\r\n");
      out.write("\t\t  \t\t\t\"render\": function(data, type, row, meta){\r\n");
      out.write("\t\t  \t            if(type === 'display'){\r\n");
      out.write("\t\t  \t                data = '<a href=\"#\" onclick=\"openReportPop(\\''+row.REPRT_NO+'\\',\\''+row.REPRT_NM+'\\')\" >'+row.REPRT_NM+'</a>';\r\n");
      out.write("\t\t  \t            }\r\n");
      out.write("\r\n");
      out.write("\t\t  \t            return data;\r\n");
      out.write("\t\t  \t         }\t\r\n");
      out.write("\t\t  \t\t},\r\n");
      out.write("\t\t  \t\t{ \"data\": '',\r\n");
      out.write("\t\t  \t\t\t\"defaultContent\" : '',\r\n");
      out.write("\t\t  \t\t\t\"render\": function(data, type, row, meta){\r\n");
      out.write("\t\t  \t            if(type === 'display'){\r\n");
      out.write("\t\t  \t            \t data = '<a href=\"#\" onclick=\"openReportList(\\''+row.CORP_CODE+'\\',\\''+row.CORP_NAME+'\\')\" class=\"btn btn-light btn-icon-split\"><span class=\"icon text-gray-600\"><i class=\"fas fa-flag\"></i></span></a>';\r\n");
      out.write("\t\t  \t            }\r\n");
      out.write("\r\n");
      out.write("\t\t  \t            return data;\r\n");
      out.write("\t\t  \t         }\t \r\n");
      out.write("\t\t  \t\t},\r\n");
      out.write("\t\t  \t\t{ \"data\": '',\r\n");
      out.write("\t\t  \t\t\t\"defaultContent\" : '',\r\n");
      out.write("\t\t  \t\t\t\"render\": function(data, type, row, meta){\r\n");
      out.write("\t\t  \t            if(type === 'display'){\r\n");
      out.write("\t\t  \t            \tdata = '<a href=\"#\" onclick=\"goPortfolioDetail(\\''+row.CORP_CODE+'\\')\" class=\"btn btn-info btn-circle btn-sm\"><i class=\"fas fa-info-circle\"></i></a>';\r\n");
      out.write("\t\t  \t            }\r\n");
      out.write("\r\n");
      out.write("\t\t  \t            return data;\r\n");
      out.write("\t\t  \t         }\t \r\n");
      out.write("\t\t  \t\t},\r\n");
      out.write("\t\t  \t\t{ \"data\": 'MEMO', \r\n");
      out.write("\t\t  \t\t\t\"render\": function(data, type, row, meta){\r\n");
      out.write("\t\t  \t\t\t\tif(row.MEMO != null && row.MEMO != ''){\r\n");
      out.write("\t\t  \t\t\t\t\tif(type === 'display'){\r\n");
      out.write("\t\t  \t\t\t\t\t\tdata = '<a href=\"#\" onclick=\"openMemoPop(\\''+row.CORP_CODE+'\\'); return false;\" style=\"border-color: #FFD232; background: #FFD232;\" class=\"btn btn-info btn-circle btn-sm\"><i class=\"fas fa-clipboard-list\"></i></a>';\r\n");
      out.write("\t\t\t  \t            }\t\t  \t\t\t\t\t\r\n");
      out.write("\t\t  \t\t\t\t}else{\r\n");
      out.write("\t\t  \t\t\t\t\tdata = '<a href=\"#\" onclick=\"openMemoPop(\\''+row.CORP_CODE+'\\'); return false;\" style=\"border-color: #aeafb9; background: #aeafb9;\" class=\"btn btn-info btn-circle btn-sm\"><i class=\"fas fa-clipboard-list\"></i></a>';\r\n");
      out.write("\t\t  \t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t  \t            return data;\r\n");
      out.write("\t\t  \t         }\t\r\n");
      out.write("\t\t  \t\t}\r\n");
      out.write("\t\t  \t]\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction delInterest(corpCd,corpNm,stockCd){\r\n");
      out.write("\t\tvar frm = document.form;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(!confirm('\\''+corpNm+'\\'을 관심목록에서 삭제하시겠습니까?')) return;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#corpCd\").val(corpCd);\r\n");
      out.write("\t\t$(\"#corpNm\").val(corpNm);\r\n");
      out.write("\t\t$(\"#stockCd\").val(stockCd);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfrm.action = \"/interest/del/cud\";\r\n");
      out.write("\t\tfrm.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction addPortfolio(corpCd,corpNm,stockCd){\r\n");
      out.write("\t\tvar url = \"/portfolio/add/cud\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(!confirm('\\''+corpNm+'\\'을 포트폴리오에 추가하시겠습니까?')) return;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({    \r\n");
      out.write("\t\t\ttype : 'post',           // 타입 (get, post, put 등등)    \r\n");
      out.write("\t\t\turl : url,           // 요청할 서버url    \r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\tCORP_CODE \t: corpCd,\r\n");
      out.write("\t\t\t\tCORP_NAME\t: corpNm,\r\n");
      out.write("\t\t\t\tSTOCK_CODE \t: stockCd,\r\n");
      out.write("\t\t\t},    \r\n");
      out.write("\t\t\tdataType : 'json',    \r\n");
      out.write("\t\t\tsuccess : function(data) { // 결과 성공 콜백함수        \r\n");
      out.write("\t\t\t\t$('#dataTables').css(\"animation-name\",\"add\");\r\n");
      out.write("\t\t\t\t$('#dataTables').css(\"animation-duration\",\"2.5s\");\r\n");
      out.write("\t\t\t},    \r\n");
      out.write("\t\t\terror : function(request, status, error) {       \r\n");
      out.write("\t\t\t\tconsole.log(error)    \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction openMemoPop(corpCd){\r\n");
      out.write("        var url = \"/popup/portfolio/memo?pCorpCd=\"+corpCd;\r\n");
      out.write("        var name = \"포트폴리오 메모 팝업\";\r\n");
      out.write("        var option = \"width = 505, height = 780, top = 100, left = 200, location = no\"\r\n");
      out.write("        window.open(url, name, option);\r\n");
      out.write("    }\r\n");
      out.write("\t\r\n");
      out.write("\tfunction openReportPop(reprtNo,reprtNm){\r\n");
      out.write("        var url = \"https://dart.fss.or.kr/dsaf001/main.do?rcpNo=\"+reprtNo;\r\n");
      out.write("        var name = reprtNm;\r\n");
      out.write("        var option = \"width = 500, height = 1500, top = 100, left = 200, location = no\"\r\n");
      out.write("        window.open(url, name, option);\r\n");
      out.write("    }\r\n");
      out.write("\t\r\n");
      out.write("\tfunction openReportList(corpCd,corpNm){\r\n");
      out.write("        var url = \"/popup/dart/report/list?corpCd=\"+corpCd;\r\n");
      out.write("        var name = corpNm + \" 공시 목록\";\r\n");
      out.write("        var option = \"width = 1000, height = 700, top = 100, left = 200, location = no\"\r\n");
      out.write("        window.open(url, name, option);\r\n");
      out.write("    }\r\n");
      out.write("\t\r\n");
      out.write("\tfunction delPortCorp(){\r\n");
      out.write("\t\tvar frm = document.searchForm;\r\n");
      out.write("\t\tvar delChks = \"\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar i = 0;\r\n");
      out.write("\t\t$(\"input[name=del_chk]:checked\").each(function(){\r\n");
      out.write("\t\t\tif(i==0){\r\n");
      out.write("\t\t\t\tdelChks += $(this).val();\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tdelChks += \",\"+$(this).val();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\ti++;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(i == 0){\r\n");
      out.write("\t\t\talert(\"삭제할 사업장을 선택해 주세요.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar corpCd = \"\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(!confirm('체크된 사업장을 포트폴리오에서 삭제하시겠습니까?')) return;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#corpCds\").val(delChks);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfrm.action = \"/portfolio/del/cud\";\r\n");
      out.write("\t\tfrm.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction regAsset(gu){\r\n");
      out.write("\t\tvar url = \"/portfolio/regasset/cud\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar guTitle = \"\";\r\n");
      out.write("\t\tvar guVal = \"\";\r\n");
      out.write("\t\tif(gu == 'deposit'){\r\n");
      out.write("\t\t\tguVal = $(\"#DEPOSIT_AMOUNT\").val();\r\n");
      out.write("\t\t\tguTitle = $(\"#DEPOSIT_AMOUNT\").attr(\"title\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tguVal = $(\"#RESERVE_AMOUNT\").val();\r\n");
      out.write("\t\t\tguTitle =  $(\"#RESERVE_AMOUNT\").attr(\"title\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tguVal = guVal.toString().replace(/\\B(?<!\\.\\d*)(?=(\\d{3})+(?!\\d))/g, \",\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\talert(guTitle + \" : \"+guVal+\" 원 등록 하시겠습니까?\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({    \r\n");
      out.write("\t\t\ttype : 'post',           // 타입 (get, post, put 등등)    \r\n");
      out.write("\t\t\turl : url,           // 요청할 서버url    \r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\tDEPOSIT_AMOUNT \t: $(\"#DEPOSIT_AMOUNT\").val(),\r\n");
      out.write("\t\t\t\tRESERVE_AMOUNT\t: $(\"#RESERVE_AMOUNT\").val(),\r\n");
      out.write("\t\t\t},    \r\n");
      out.write("\t\t\tdataType : 'json',    \r\n");
      out.write("\t\t\tsuccess : function(data) { // 결과 성공 콜백함수\r\n");
      out.write("\t\t\t\tvar resultData = data.resultData;\r\n");
      out.write("\t\t\t\tif(gu == 'deposit'){\r\n");
      out.write("\t\t\t\t\t$(\"btn_DEPOSIT_AMOUNT\").text('수정');\r\n");
      out.write("\t\t\t\t\t$(\"#DEPOSIT_AMOUNT\").val(resultData.DEPOSIT_AMOUNT);\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$(\"btn_RESERVE_AMOUNT\").text('수정');\r\n");
      out.write("\t\t\t\t\t$(\"#RESERVE_AMOUNT\").val(resultData.RESERVE_AMOUNT);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$('#cardDiv').css(\"animation-name\",\"add\");\r\n");
      out.write("\t\t\t\t$('#cardDiv').css(\"animation-duration\",\"2.5s\");\r\n");
      out.write("\t\t\t},    \r\n");
      out.write("\t\t\terror : function(request, status, error) {       \r\n");
      out.write("\t\t\t\tconsole.log(error)    \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction goPortfolioDetail(corpCd){\r\n");
      out.write("\t\tvar frm = document.searchForm;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#pCorpCd\").val(corpCd);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfrm.action = \"/portfolio/detail\";\r\n");
      out.write("\t\tfrm.target = \"_blank\"\r\n");
      out.write("\t\tfrm.submit();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("@keyframes add {\r\n");
      out.write("\tfrom{background : lightgreen;}\r\n");
      out.write("\tto{background : transparent;}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes del {\r\n");
      out.write("\tfrom{background : indianred;}\r\n");
      out.write("\tto{background : transparent;}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes search {\r\n");
      out.write("\tfrom{background : lightsteelblue;}\r\n");
      out.write("\tto{background : transparent;}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>사업장 목록</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("\t<form name=\"searchForm\" method=\"post\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"CORP_CODE\" id=\"CORP_CODE\" value=\"\" title=\"기업 코드\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"STOCK_CODE\" id=\"STOCK_CODE\" value=\"\" title=\"기업 코드\">\r\n");
      out.write("\t\r\n");
      out.write("\t<input type=\"hidden\" name=\"pCorpCd\" id=\"pCorpCd\" value=\"\" title=\"검색용 기업 코드\">\r\n");
      out.write("\t\r\n");
      out.write("\t<input type=\"hidden\" name=\"corpCds\" id=\"corpCds\" value=\"\" title=\"삭제대상 사업장코드(복수)\">\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Page Heading -->\r\n");
      out.write("\t<h1 class=\"h3 mb-2 text-gray-800\">포트폴리오</h1>\r\n");
      out.write("\t<p class=\"mb-4\">본인이 보유하고 있는 기업에 대한 포트폴리오 리스트 \r\n");
      out.write("\t\t<span id=\"\"></span>\r\n");
      out.write("\t</p>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"col-xl-4 col-lg-5\">\r\n");
      out.write("\t    <div class=\"card shadow mb-4\" id=\"cardDiv\">\r\n");
      out.write("\t        <!-- Card Header - Dropdown -->\r\n");
      out.write("\t        <div class=\"card-header py-3 d-flex flex-row align-items-center justify-content-between\">\r\n");
      out.write("\t            <h6 class=\"m-0 font-weight-bold text-primary\">포트폴리오 자산 분배비율</h6>\r\n");
      out.write("\t            <div class=\"dropdown no-arrow\">\r\n");
      out.write("\t                <a class=\"dropdown-toggle\" href=\"#\" role=\"button\" id=\"dropdownMenuLink\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("\t                    <i class=\"fas fa-ellipsis-v fa-sm fa-fw text-gray-400\"></i>\r\n");
      out.write("\t                </a>\r\n");
      out.write("\t                <div class=\"dropdown-menu dropdown-menu-right shadow animated--fade-in\" aria-labelledby=\"dropdownMenuLink\">\r\n");
      out.write("\t                    <div class=\"dropdown-header\" style=\"font-size: 12px;\">- 자산 등록 -</div>\r\n");
      out.write("\t                    <div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t                    <div style=\"padding: 5px 10px 5px 10px;\">\r\n");
      out.write("\t\t                    <div class=\"dropdown-item\" style=\"padding: 10px 10px 10px 10px;\">\r\n");
      out.write("\t\t\t                    예수금 : <input type=\"text\" name=\"DEPOSIT_AMOUNT\" id=\"DEPOSIT_AMOUNT\" style=\"width : 135px;\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${getPortfolio.DEPOSIT_AMOUNT }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  title=\"예수금\" placeholder=\"예수금\"> \r\n");
      out.write("\t\t\t                    <button class=\"btn btn-outline-primary\" style=\"height: 30px; font-size: 13px; width: 55px;\" id=\"btn_DEPOSIT_AMOUNT\" onclick=\"regAsset('deposit'); return false;\">\r\n");
      out.write("\t\t\t                    \t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t                    \t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t                    </button>\r\n");
      out.write("\t\t                    </div>\r\n");
      out.write("\t\t                    <div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t\t                    <div class=\"dropdown-item\" style=\"padding: 10px 10px 10px 10px;\">\r\n");
      out.write("\t\t\t                    예비금 : <input type=\"text\" name=\"RESERVE_AMOUNT\" id=\"RESERVE_AMOUNT\" style=\"width : 135px;\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${getPortfolio.RESERVE_AMOUNT }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  title=\"예비금\" placeholder=\"예비금\"> \r\n");
      out.write("\t\t\t                    <button class=\"btn btn-outline-primary\" style=\"height: 30px; font-size: 13px; width: 55px;\" id=\"btn_RESERVE_AMOUNT\" onclick=\"regAsset('reserve'); return false;\">\r\n");
      out.write("\t\t\t                    \t");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t                    \t");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("\t\t\t                    </button>\r\n");
      out.write("\t\t                    </div>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <!-- Card Body -->\r\n");
      out.write("\t        <div class=\"card-body\">\r\n");
      out.write("\t            <div class=\"chart-pie pt-4 pb-2\"><div class=\"chartjs-size-monitor\"><div class=\"chartjs-size-monitor-expand\"><div class=\"\"></div></div><div class=\"chartjs-size-monitor-shrink\"><div class=\"\"></div></div></div>\r\n");
      out.write("\t                <canvas id=\"myPieChart\" width=\"470\" height=\"245\" style=\"display: block; width: 470px; height: 245px;\" class=\"chartjs-render-monitor\"></canvas>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <div class=\"mt-4 text-center small\">\r\n");
      out.write("\t                <span class=\"mr-2\">\r\n");
      out.write("\t                    <i class=\"fas fa-circle text-primary\"></i> 예수금\r\n");
      out.write("\t                </span>\r\n");
      out.write("\t                <span class=\"mr-2\">\r\n");
      out.write("\t                    <i class=\"fas fa-circle text-success\"></i> 투자금\r\n");
      out.write("\t                </span>\r\n");
      out.write("\t                <span class=\"mr-2\">\r\n");
      out.write("\t                    <i class=\"fas fa-circle text-info\"></i> 예비금\r\n");
      out.write("\t                </span>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<!-- DataTales Example -->\r\n");
      out.write("    <div class=\"card shadow mb-4\">\r\n");
      out.write("        <div class=\"card-header py-3\" id=\"dataTables\" style=\"display: table;\">\r\n");
      out.write("            <h6 class=\"m-0 font-weight-bold text-primary\" style=\"display: table-cell; width: 95%; padding-left: 10px;\">포트폴리오 기업목록</h6>\r\n");
      out.write("            <div >\r\n");
      out.write("\t\t\t\t<button class=\"dt-button buttons-excel buttons-html5 btn btn-outline-primary excelBtn\" style=\"width: 70px;\" tabindex=\"0\" aria-controls=\"portCorpList\" onclick=\"delPortCorp(); return false;\">\r\n");
      out.write("\t\t\t\t\t<span>삭제</span>\r\n");
      out.write("\t\t\t\t</button>                \t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("            <div class=\"table-responsive\" >\r\n");
      out.write("                <table id=\"portCorpList\" class=\"table table-bordered\" id=\"dataTable\" width=\"100%\" >\r\n");
      out.write("                    <thead id=\"tableHead\">\r\n");
      out.write("\t\t\t            <tr>\r\n");
      out.write("\t\t\t            \t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>투자의견</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>사업장명</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>전일종가</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>평균단가</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>보유수량</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>최근공시명</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>공시목록</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>상세</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>메모</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t        </thead>\r\n");
      out.write("\t\t\t        <tbody id=\"bodyList\">\r\n");
      out.write("\t\t\t        </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
>>>>>>> 844a58f86eba82bf22f4b63666f11ea8363e93f4
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/portfolio/portfolioList.jsp(349,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${getPortfolio.DEPOSIT_AMOUNT != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('수');
          out.write('정');
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/portfolio/portfolioList.jsp(350,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${getPortfolio.DEPOSIT_AMOUNT == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('등');
          out.write('록');
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/portfolio/portfolioList.jsp(357,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${getPortfolio.RESERVE_AMOUNT != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('수');
          out.write('정');
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/views/portfolio/portfolioList.jsp(358,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${getPortfolio.RESERVE_AMOUNT == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('등');
          out.write('록');
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }
}
